version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229" # Node.js debug port
      - "8969:8969"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: node --inspect=0.0.0.0:9229 node_modules/.bin/astro dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "5678:5678" # Expose the debug port
    volumes:
      - ./backend:/usr/src/app
    environment:
      - ENV_FILE=.env
    command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m uvicorn app.main:app --host 0.0.0.0 --port 8000